name: 'tdlib'
description: 'A sample command-line application.'
version: '1.8.32'
environment: 
  sdk: '^3.3.4'
dependencies: 
  packagex: '^0.0.58'
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
  msix: '^3.16.7'
packagex: 
  name: 'tdlib'
  dart_target: 'tdlib'
  flutter_target: 'main'
  dart_name: 'tdlib'
  flutter_name: 'tdlib'
  is_without_platform_name: true
  flutter_commands: 
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  project_id: 'azkadev.packagex'
  github_username: 'azkadev'
  github_is_org: false
msix_config: 
  display_name: 'tdlib'
  install_certificate: false
